#!/usr/bin/ksh
# determine e1 app server state
rg_srv="sdacwls561"
rg_host=$(ssh root@$rg_srv hostname)
instance=jde920
node=$(hostname)
if [ $rg_host == $node ];
then 
#state=$(e1d ${instance} status | sed '1,1d' | awk {'print $2'})
#echo $state
state="UP"
if [ $state != "UP" ] ;
 then
	
   STATUS=2
   echo $STATUS ${rg_srv}_home HOME=$rg_host CRITICAL - Resource Group $rg_srv.rg should be running, but does not!
#   exit $STATUS
else 
   STATUS=0
   echo "$STATUS ${rg_srv}_home HOME=$rg_host OK - Resource Group $rg_srv.rg is running on node $node" 
#   exit $STATUS
fi;
else
	STATUS=3
   echo $STATUS ${rg_srv}_home HOME=$rg_host OK - Node $node is not Resource Group HOME 
#   exit $STATUS
fi;
 
